package de.bossascrew.shops.util;

public enum ShopAction {

	RIGHT_CLICK_SHOP,
	LEFT_CLICK_SHOP,
	SHIFT_RIGHT_CLICK_SHOP,
	SHIFT_LEFT_CLICK_SHOP,
	MOUSE_WHEEL_SHOP,
	DOUBLE_CLICK_SHOP,
	RIGHT_CLICK_INV,
	LEFT_CLICK_INV,
	SHIFT_RIGHT_CLICK_INV,
	SHIFT_LEFT_CLICK_INV,
	MOUSE_WHEEL_INV,
	DOUBLE_CLICK_INV,
}
