package de.bossascrew.shops.statshops.shop;

public enum EntryInteractionResult {
	STATIC,
	FAIL_NOT_PURCHASABLE,
	FAIL_NOT_SELLABLE,
	FAIL_UNKNOWN,
	FAIL_SHOP_DISABLED,
	FAIL_VAULT_UNKNOWN,
	FAIL_NO_ENTRY,
	FAIL_NO_PERMISSION,
	FAIL_CANT_AFFORD,
	FAIL_CANT_REWARD,
	SUCCESS
}
