package de.bossascrew.shops.shop.entry;

public enum DefaultShopType {

	STATIC,
	MONEY_FOR_COMMANDS,
	ITEMS_FOR_COMMANDS,
	MONEY_FOR_ITEMS,
	ITEMS_FOR_MONEY,
	ITEMS_FOR_ITEMS,
	NEXT_PAGE,
	PREV_PAGE,
	PRECISE_PAGE,
	NEXT_MODE,
	PREV_MODE,
	PRECISE_MODE
}
